### ISSUE TITLE
Extracted filename format

### ISSUE THREAD

**Issue by drebrez** [PabloCastellano/extract-dtb#1]
@PabloCastellano could you please add a leading 0 to the number in the filename? 
like this:
```
dtbdump_01.dtb
dtbdump_02.dtb
dtbdump_03.dtb
dtbdump_04.dtb
dtbdump_05.dtb
dtbdump_06.dtb
dtbdump_07.dtb
dtbdump_08.dtb
dtbdump_09.dtb
dtbdump_10.dtb
dtbdump_11.dtb
dtbdump_12.dtb
...
```

**Comment by drebrez** [comment]
With `dtb_filename = "dtbdump_{0:0>2}.dtb".format(n)`  works like a charm

**Comment by PabloCastellano** [comment]
Looks good to me. Would like mind submitting a PR for both this issue and https://github.com/PabloCastellano/extract-dtb/issues/2 ?
