### ISSUE TITLE
coding error

### ISSUE THREAD

**Issue by yatescr** [PabloCastellano/extract-dtb#10]
Line 45 of extract_dtb.py has an erroneous "arg" prefix in the first argument:

ret = os.path.join(args.output_dir, dtb_filename_new)

and should be 

ret = os.path.join(output_dir, dtb_filename_new)

**Comment by SebaUbuntu** [comment]
Opened a PR for this https://github.com/PabloCastellano/extract-dtb/pull/11

**Comment by PabloCastellano** [comment]
Fixed and released version 1.2.2 :+1:
