### ISSUE TITLE
escape new lines in filename

### ISSUE THREAD

**Issue by yokrysty** [PabloCastellano/extract-dtb#14]
hello, first of all nice work, very useful tool

I had encountered an error when dtb_filename would contain new line (\n)
![image](https://user-images.githubusercontent.com/9500609/138506395-b550ecf6-b40d-4b97-bae5-0c2b5015e23e.png)
i did a simple fix of replacing that char with nothing, but maybe you would want to do more sanitization than this, for other illegal chars, if not you can ignore this issue
![image](https://user-images.githubusercontent.com/9500609/138506630-3699b67b-a3c9-45e2-ac03-1e7c546714fe.png)

cheers

**Comment by PabloCastellano** [comment]
Fixed by https://github.com/PabloCastellano/extract-dtb/pull/16 . Thanks!
