### ISSUE TITLE
Command issue:  ./extract-dtb.py

### ISSUE THREAD

**Issue by sdembis** [PabloCastellano/extract-dtb#15]
FYI:  You indicate the command as:  ./extract-dtb.py
It should be: ./extract_dtb.py
i.e., underscore not dash between extract and dtb.py

A small issue but confusing until looked at a bit more closely.

Appreciate your work - ran like a charm, once I realized the command issue.

Cheers,
S.

**Comment by PabloCastellano** [comment]
Fixed, thanks!
