### ISSUE TITLE
DTBO.img

### ISSUE THREAD

**Issue by kondors1995** [PabloCastellano/extract-dtb#17]
cna this be used to extract dtbo.img

**Comment by PabloCastellano** [comment]
@kondors1995 What do you mean? Can you provide some example?

**Comment by kondors1995** [comment]
on A only SAR, we have dtb partition that contains devices' dtb files.
I would like to try to extract dtb out of this image file so I can reverse engineer few trimmings for panel

**Comment by PabloCastellano** [comment]
Can you paste the output of `extract-dtb <filename>`?

**Comment by kondors1995** [comment]
sure once i get home

**Comment by George-Seven** [comment]
@kondors1995 it's been more than half a year, you should choose a closer residence the next chance you get. Jokes aside, any progress?

**Comment by kondors1995** [comment]
sorry for late repply lets close this one. With my ADHD brain, I forgot to reply to results & now I have 0 clues what I was working on.
