### ISSUE TITLE
I can't extract a boot.img

### ISSUE THREAD

**Issue by doomlord77** [PabloCastellano/extract-dtb#5]
Hi!

I have phyton installed and when I run the command "extract-dtb.py C:\boot.img" I get an error: 
usage: extract-dtb.py [-h] [-o OUTPUT_DIR] [-n] [-V] filename
extract-dtb.py: error: the following arguments are required: filename

But I have a boot.img file in the C:\ path. Same with "extract-dtb.py boot.img" when extract-dtb.py and boot.img are in the same folder. What should I do?

**Comment by chankruze** [comment]
@doomlord77 you are not specifying an output folder path.

For example:
```
extract-dtb.py -o extracted-dtbs ../boot.img
```

This will extract the dtbs from boot image which is one directory up relative to script & save them to same directory where script is in a folder named as extracted-dtbs (it'll create this folder automatically).

**Comment by doomlord77** [comment]
I don't even know what I wanted to do with that script but thanks
for letting me know. I will remeber it in the future!

**Comment by PabloCastellano** [comment]
I'm closing this issue after @doomlord77's comment. Don't hesitate to reopen if needed.
