### ISSUE TITLE
Extract dtb  an error occurreda

### ISSUE THREAD

**Issue by zszszszsz** [PabloCastellano/extract-dtb#8]
I have a Chinese TVbox and i got the update.zip .When i unpack it ,i got the dtb.img so i want to use this tool to extract dtb.But something wrong is that it display：“FATAL ERROR: Blob has incorrect magic number“.

**Comment by PabloCastellano** [comment]
Hi @zszszszsz Can you upload the image somewhere so I can have a look?

**Comment by zszszszsz** [comment]
sorry，the problem is not in this tool.But i cant extract dtb not only in dtb.img ,but also in dtb.img.
I really appreciate your help。
![批注 2020-04-25 223924](https://user-images.githubusercontent.com/56225718/80282818-18b1fe00-8746-11ea-8f8d-40ef4e513d67.png)

**Comment by zszszszsz** [comment]
The problem has been solved.
first of all，i use split_bootimg.pl to unpack boot.img .
And then i use your tool to extract the dt.img.
thank you！
![批注 2020-04-25 225541](https://user-images.githubusercontent.com/56225718/80283109-f7521180-8747-11ea-9f71-fb6191a0be36.png)

**Comment by PabloCastellano** [comment]
Good to see you solved it!
